### ISSUE TITLE
faltan datos en algunos modelos.

### ISSUE THREAD

**Issue by Kartaan** [Juan-Felipe18/Sociald-proyect#1]
siguendo el diagrama compartido, hay algunos datos que no pude comprender su tipo ni como agregarlos asi que los omiti. (estan en rojo en el diagrama).

faltarian los repositorios y las relaciones.

**Comment by juanhenaoparra** [comment]
Bien, el campo _skills_ en **Person** es un array de strings. El campo _cv_ yo creo que puede quitarse, ya que eso lo vamos haciendo por medio de relaciones y consultas. Y el campo _rate_ en **Service** no se que es. (@Juan-Felipe18 )

**Comment by Juan-Felipe18** [comment]
El rate seria la calificación que le da una empresa a una persona, para saber que tan bueno es.

**Comment by juanhenaoparra** [comment]
Ya, entonces no debería ser un campo sino un modelo aparte. O podría estar en  el modelo service.

**Comment by Juan-Felipe18** [comment]
Seria un **type number** en **service** por que es un atributo que tiene el servicio o bueno la persona.
